"""Content bank models for pre-generated scripts and batch jobs."""
from datetime import datetime
from typing import Literal, Optional, List

from pydantic import BaseModel, Field


BankStatus = Literal["draft", "approved", "archived"]
BankSource = Literal["manual", "ai_batch", "import"]


class BankItemBase(BaseModel):
    """Shared fields for content bank items."""

    # Core creative fields
    title: str = Field(..., description="Short hook-style title for the script (what user sees in bank).")
    script: str = Field(..., description="Full talking script for the video.")
    caption: str = Field(..., description="Caption text including hashtags, already compliant.")
    content_pillar: str = Field(..., description="education | routine | story | product_integration, etc.")
    tone: str = Field(..., description="friendly | educational | etc.")
    length_seconds: Optional[int] = Field(
        None, description="Approx expected video length; used for filtering and TikTok best practices."
    )

    # Lifecycle & provenance
    status: BankStatus = Field(
        "draft",
        description="draft = needs review, approved = safe for dad to use, archived = hidden from main view.",
    )
    created_from: BankSource = Field(
        "ai_batch",
        description="manual = hand-written, ai_batch = generated by batch pipeline, import = CSV or other.",
    )

    # Diversity / series metadata
    topic_cluster: Optional[str] = Field(
        None,
        description="Loose topic grouping used to avoid repetitive scheduling (e.g., 'afternoon_energy').",
    )
    series_name: Optional[str] = Field(
        None,
        description="Optional series label, e.g., 'Energy Tip Tuesday'.",
    )
    target_problem: Optional[str] = Field(
        None,
        description="Short description of the viewer problem this script addresses.",
    )

    # Media / render state
    voiceover_url: Optional[str] = Field(
        None,
        description="URL to generated voiceover audio file, if available.",
    )
    primary_asset_url: Optional[str] = Field(
        None,
        description="Main image or video asset URL to feed into Creatomate.",
    )
    secondary_asset_url: Optional[str] = Field(
        None,
        description="Optional second asset (e.g., another clip) for multi-shot templates.",
    )
    rendered_video_url: Optional[str] = Field(
        None,
        description="URL of the most recent rendered video for this bank item.",
    )
    last_render_status: Optional[str] = Field(
        None,
        description="Last known render status: pending, succeeded, failed, etc.",
    )

    # Usage & basic analytics
    times_used: int = Field(0, description="How many times this item has been used to render a video.")
    last_used_at: Optional[datetime] = Field(
        None,
        description="When this script was last used to create a video.",
    )
    posted_at: Optional[datetime] = Field(
        None,
        description="When this content was actually posted to social (manual entry).",
    )
    platforms: Optional[str] = Field(
        None,
        description="Comma-separated list of platforms where this content was posted.",
    )
    performance_notes: Optional[str] = Field(
        None,
        description="Optional human-entered notes about performance/feedback.",
    )


class BankItemCreate(BankItemBase):
    """Payload to create a new content bank item."""

    pass


class BankItemUpdate(BaseModel):
    """Partial update for bank items (script tweaks, status changes, etc.)."""

    title: Optional[str] = None
    script: Optional[str] = None
    caption: Optional[str] = None
    content_pillar: Optional[str] = None
    tone: Optional[str] = None
    length_seconds: Optional[int] = None
    status: Optional[BankStatus] = None


class BankItem(BankItemBase):
    """Response model for bank items."""

    id: int
    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True


class BankItemFilters(BaseModel):
    """Query params for listing/filtering the content bank."""

    search: Optional[str] = None
    status: Optional[BankStatus] = None
    content_pillar: Optional[str] = None
    tone: Optional[str] = None
    max_length_seconds: Optional[int] = None
    min_length_seconds: Optional[int] = None
    limit: int = 50


class BatchJobBase(BaseModel):
    """Base fields for tracking batch jobs (content generation, rendering, etc.)."""

    type: Literal["content_generation", "video_render"]
    payload_json: dict
    status: Literal["pending", "running", "succeeded", "failed"] = "pending"
    progress: int = 0
    error: Optional[str] = None


class BatchJob(BatchJobBase):
    id: int
    created_at: datetime
    completed_at: Optional[datetime] = None

    class Config:
        from_attributes = True


class BatchGenerateRequest(BaseModel):
    """Request payload for batch content generation."""

    topic_theme: str = Field(..., description="High-level theme (e.g., 'afternoon energy', 'evening routines')")
    content_pillars: List[str] = Field(
        ..., description="List of pillars to generate (e.g., ['education', 'routine'])"
    )
    tone: str = Field("friendly", description="Tone for all generated content")
    count: int = Field(10, ge=1, le=50, description="Number of items to generate")
    min_length_seconds: int = Field(15, ge=10, le=60, description="Target minimum video length")
    max_length_seconds: int = Field(45, ge=15, le=120, description="Target maximum video length")
    topic_cluster: Optional[str] = Field(
        None, description="Optional cluster name for grouping (e.g., 'afternoon_energy')"
    )
    series_name: Optional[str] = Field(
        None, description="Optional series name (e.g., 'Energy Tip Tuesday')"
    )
    similarity_threshold: float = Field(
        0.4, ge=0.0, le=1.0, description="Threshold for duplicate detection (0.0-1.0)"
    )


class BatchRenderRequest(BaseModel):
    """Request payload for batch video rendering."""

    content_ids: Optional[List[int]] = Field(
        None,
        description="List of content bank item IDs to render. If provided, filter_criteria is ignored.",
    )
    filter_criteria: Optional[dict] = Field(
        None,
        description="Filter criteria to find items to render (e.g., {'status': 'approved', 'not_rendered': True}).",
    )
    template_type: str = Field("video", description="'image' or 'video' template to use")
    with_voiceover: bool = Field(True, description="Generate voiceover if missing")
    priority: str = Field("normal", description="'low' or 'normal' priority")
